// Bundles server/main.ts (+ the shared bill/ID/cost code) into one Apps Script file.
import { build } from 'esbuild'
import { writeFileSync } from 'node:fs'

const r = await build({
  entryPoints: ['server/main.ts'], bundle: true, format: 'iife', globalName: 'Anavrin',
  target: 'es2019', platform: 'neutral', write: false, legalComments: 'none', charset: 'utf8',
})
const stubs = `
// ---- entry points Apps Script calls ----
function doGet(e) { return Anavrin.doGet(e) }
function doPost(e) { return Anavrin.doPost(e) }
/** Run this once after pasting the code (select "setup" above, then Run). */
function setup() { return Anavrin.setup() }
`
const header = '// Anavrin server for Google Apps Script — generated by `npm run build:server`. Paste this whole file into Code.gs.\n'
writeFileSync('apps-script/Code.gs', header + r.outputFiles[0].text + stubs)
console.log('apps-script/Code.gs', (r.outputFiles[0].text.length / 1024).toFixed(0) + ' KB')
