// Anavrin server for Google Apps Script — generated by `npm run build:server`. Paste this whole file into Code.gs.
var Anavrin = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // server/main.ts
  var main_exports = {};
  __export(main_exports, {
    applyOps: () => applyOps,
    doGet: () => doGet,
    doPost: () => doPost,
    getPhoto: () => getPhoto,
    handle: () => handle,
    readBill: () => readBill,
    readState: () => readState,
    savePhoto: () => savePhoto,
    savePurchase: () => savePurchase,
    setup: () => setup
  });

  // src/lib/bill.ts
  var MONTHS = {
    jan: "01",
    feb: "02",
    mar: "03",
    apr: "04",
    may: "05",
    jun: "06",
    jul: "07",
    aug: "08",
    sep: "09",
    oct: "10",
    nov: "11",
    dec: "12"
  };
  var r2 = (n) => Math.round(n * 100) / 100;
  function toNum(v) {
    if (typeof v === "number") return Number.isFinite(v) ? v : null;
    if (typeof v !== "string") return null;
    const s = v.replace(/[₹,\s]|rs\.?|inr|pcs?/gi, "");
    if (!s) return null;
    const n = Number(s);
    return Number.isFinite(n) ? n : null;
  }
  function toIsoDate(v) {
    if (typeof v !== "string") return null;
    const s = v.trim();
    let m = s.match(/^(\d{4})-(\d{2})-(\d{2})$/);
    if (m) return s;
    m = s.match(/^(\d{1,2})[/.-](\d{1,2})[/.-](\d{2}|\d{4})$/);
    if (m) return iso(m[3], m[2], m[1]);
    m = s.match(/^(\d{1,2})[\s/.-]([A-Za-z]{3})[A-Za-z]*[\s/.-](\d{2}|\d{4})$/);
    if (m && MONTHS[m[2].toLowerCase()]) return iso(m[3], MONTHS[m[2].toLowerCase()], m[1]);
    return null;
  }
  function iso(y, mo, d) {
    const yyyy = y.length === 2 ? `20${y}` : y;
    const out = `${yyyy}-${mo.padStart(2, "0")}-${d.padStart(2, "0")}`;
    return Number.isNaN(Date.parse(out)) ? null : out;
  }
  var DOC_TYPES = ["tax_invoice", "quotation", "estimate", "other"];
  function normalizeBill(raw) {
    const o = raw && typeof raw === "object" ? raw : {};
    const str = (v) => typeof v === "string" && v.trim() ? v.trim() : null;
    const lines = Array.isArray(o.lines) ? o.lines : [];
    return {
      vendorName: str(o.vendorName),
      vendorGstin: str(o.vendorGstin),
      docType: DOC_TYPES.includes(o.docType) ? o.docType : "other",
      billNo: str(o.billNo),
      billDate: toIsoDate(o.billDate),
      buyer: str(o.buyer),
      lines: lines.map((l) => {
        var _a, _b, _c, _d, _e;
        const x = l != null ? l : {};
        return {
          description: (_a = str(x.description)) != null ? _a : "",
          hsn: str(String((_b = x.hsn) != null ? _b : "")),
          qty: (_c = toNum(x.qty)) != null ? _c : 0,
          rate: (_d = toNum(x.rate)) != null ? _d : 0,
          discountPct: toNum(x.discountPct),
          amount: (_e = toNum(x.amount)) != null ? _e : 0
        };
      }),
      totalQty: toNum(o.totalQty),
      subtotal: toNum(o.subtotal),
      cgst: toNum(o.cgst),
      sgst: toNum(o.sgst),
      igst: toNum(o.igst),
      roundOff: toNum(o.roundOff),
      grandTotal: toNum(o.grandTotal),
      handwrittenNotes: (Array.isArray(o.handwrittenNotes) ? o.handwrittenNotes : []).map((h) => {
        var _a;
        const x = h != null ? h : {};
        return { text: (_a = str(x.text)) != null ? _a : "", amount: toNum(x.amount) };
      }),
      paidStamp: o.paidStamp === true,
      warnings: (Array.isArray(o.warnings) ? o.warnings : []).filter((w) => typeof w === "string")
    };
  }
  var sum = (xs) => r2(xs.reduce((a, b) => a + b, 0));
  function unitCost(line, b, opts) {
    var _a, _b;
    const base = line.qty ? line.amount / line.qty : 0;
    const subtotal = (_a = b.subtotal) != null ? _a : sum(b.lines.map((l) => l.amount));
    const grand = (_b = b.grandTotal) != null ? _b : subtotal;
    let factor = opts.gstRegistered || !subtotal ? 1 : grand / subtotal;
    const adj = opts.adjustment;
    if (adj && adj.reason === "discount" && adj.amount > 0 && grand > 0) factor *= (grand - adj.amount) / grand;
    return r2(base * factor);
  }

  // src/lib/extract/prompt.ts
  var BILL_PROMPT = `You are reading a photo of a saree wholesaler's bill from Bengaluru, India
(a GST tax invoice, a "quotation" or an estimate). Extract it exactly as printed.

Reply with ONLY one JSON object, no other text, in this shape:
{
  "vendorName": string|null,          // the SELLER at the top, e.g. "THE ROYAL THREADS"
  "vendorGstin": string|null,
  "docType": "tax_invoice"|"quotation"|"estimate"|"other",
  "billNo": string|null,              // invoice / QTN number exactly as printed, e.g. "OT001058", "PS-2713/2026-27"
  "billDate": string|null,            // as YYYY-MM-DD. Indian format: 07/08/2026 is 7 August 2026
  "buyer": string|null,               // the "Buyer"/"M/s" name if printed
  "lines": [ { "description": string, "hsn": string|null, "qty": number, "rate": number,
               "discountPct": number|null, "amount": number } ],
  "totalQty": number|null,            // the printed total pieces
  "subtotal": number|null,            // taxable value before GST
  "cgst": number|null, "sgst": number|null, "igst": number|null,   // tax AMOUNTS in rupees, not rates
  "roundOff": number|null,
  "grandTotal": number|null,
  "handwrittenNotes": [ { "text": string, "amount": number|null } ],
  "paidStamp": boolean,
  "warnings": [string]
}

Rules:
- One entry in "lines" per printed item row, in order. Do not merge or split rows.
- Read each row straight across. Photos are often tilted or the paper is curved, so the
  description column can look shifted by a row against the number columns. Match rows by
  serial number and by position, and confirm every row with qty × rate = amount.
- Quantities are whole pieces. Ignore pen tick marks or slashes drawn over numbers
  ("3/Pcs" with a tick is 3).
- Numbers: plain numbers without commas or currency symbols (1,935.00 → 1935).
- Handwritten pen notes near the total (e.g. "-5000" then "16105") go in handwrittenNotes,
  with "amount" as a signed number (-5000). Do not change the printed totals because of them.
- paidStamp is true only if a rubber stamp saying PAID is visible.
- If something is unreadable use null and add a short warning. Never invent a value.
- If qty × rate ≠ amount for a row, or the rows do not add up to the subtotal, keep what is
  printed and add a warning naming the row.`;

  // src/lib/ops.ts
  var upsert = (xs, x, key) => {
    const k = key(x);
    return xs.some((y) => key(y) === k) ? xs.map((y) => key(y) === k ? x : y) : [...xs, x];
  };
  function applyOp(s, e) {
    const { op, by, at } = e;
    switch (op.t) {
      case "saveUser":
        return { ...s, users: upsert(s.users, op.u, (u) => u.id) };
      case "saveVendor":
        return { ...s, vendors: upsert(s.vendors, op.v, (v) => v.id) };
      case "deleteVendor":
        return { ...s, vendors: s.vendors.filter((v) => v.id !== op.id) };
      case "saveType":
        return { ...s, types: upsert(s.types, op.type, (t) => t.code) };
      case "deleteType":
        return { ...s, types: s.types.filter((t) => t.code !== op.code) };
      case "saveSettings":
        return { ...s, settings: op.s };
      case "setPurchaseDeleted":
        return {
          ...s,
          purchases: s.purchases.map((p) => p.id === op.id ? { ...p, deleted: op.deleted, updatedBy: by, updatedAt: at } : p),
          items: s.items.map((i) => i.purchaseId === op.id ? { ...i, deleted: op.deleted, updatedBy: by, updatedAt: at } : i)
        };
      case "updateItems": {
        const ids = new Set(op.ids);
        return { ...s, items: s.items.map((i) => ids.has(i.id) ? { ...i, ...op.patch, updatedBy: by, updatedAt: at } : i) };
      }
    }
  }

  // src/lib/ids.ts
  var pad = (n, w) => String(n).padStart(w, "0");
  function yymm(isoDate) {
    const [y, m] = isoDate.split("-");
    return `${y.slice(2)}${m}`;
  }
  var itemId = (type, isoDate, seq) => `${type}-${yymm(isoDate)}-${pad(seq, 3)}`;
  var purchaseId = (isoDate, seq) => `P-${yymm(isoDate)}-${pad(seq, 3)}`;
  var itemCounterKey = (type, isoDate) => `item_${type}_${yymm(isoDate)}`;
  var purchaseCounterKey = (isoDate) => `purchase_${yymm(isoDate)}`;

  // src/lib/purchase.ts
  var titleCase = (s) => s.toLowerCase().replace(/\s+/g, " ").trim().replace(/(^|[\s(/-])([a-z])/g, (_, a, b) => a + b.toUpperCase());
  function buildPurchase(d, counters, settings, by, now = Date.now()) {
    const next = { ...counters };
    const take = (k) => {
      var _a;
      return next[k] = ((_a = next[k]) != null ? _a : 0) + 1;
    };
    const pid = purchaseId(d.billDate, take(purchaseCounterKey(d.billDate)));
    const asBill = normalizeBill({ ...d, lines: d.lines, grandTotal: d.grandTotal, subtotal: d.subtotal });
    const stamp = { createdBy: by.id, createdAt: now, updatedBy: by.id, updatedAt: now };
    const items = [];
    const lines = d.lines.map((l) => {
      const cost = unitCost(l, asBill, { gstRegistered: settings.gstRegistered, adjustment: d.adjustment });
      const ids = [];
      for (let k = 0; k < l.qty; k++) {
        const id = itemId(l.type, d.billDate, take(itemCounterKey(l.type, d.billDate)));
        ids.push(id);
        items.push({
          id,
          type: l.type,
          design: titleCase(l.description),
          purchaseId: pid,
          vendorId: d.vendorId,
          vendorName: d.vendorName,
          purchaseDate: d.billDate,
          cost,
          price: null,
          status: "unpriced",
          ...stamp
        });
      }
      return { ...l, unitCost: cost, itemIds: ids };
    });
    const purchase = {
      id: pid,
      vendorId: d.vendorId,
      vendorName: d.vendorName,
      billNo: d.billNo,
      billDate: d.billDate,
      docType: d.docType,
      lines,
      totalQty: lines.reduce((a, l) => a + l.qty, 0),
      subtotal: d.subtotal,
      tax: d.tax,
      roundOff: d.roundOff,
      grandTotal: d.grandTotal,
      adjustment: d.adjustment,
      amountPaid: d.amountPaid,
      photoRefs: d.photoRefs,
      readByAi: d.readByAi,
      checksOverridden: d.checksOverridden,
      ...stamp
    };
    return { purchase, items, counters: next };
  }

  // src/data/seed.ts
  var DEFAULT_TYPES = [
    { code: "KAN", name: "Kanjeevaram" },
    { code: "BAN", name: "Banarasi" },
    { code: "MYS", name: "Mysore silk" },
    { code: "CHN", name: "Chanderi" },
    { code: "PCH", name: "Pochampally / Ikat" },
    { code: "CTN", name: "Cotton / Mul" },
    { code: "LIN", name: "Linen" },
    { code: "ORG", name: "Organza" },
    { code: "GEO", name: "Georgette / Chiffon" },
    { code: "VIS", name: "Viscose" },
    { code: "ART", name: "Art silk / Semi-silk" },
    { code: "DES", name: "Designer / Fancy" },
    { code: "OTH", name: "Other" }
  ];
  var DEFAULT_VENDORS = [
    { id: "royal-threads", name: "The Royal Threads", defaultType: "VIS" },
    { id: "popular-silk", name: "Popular Silk", defaultType: "OTH" },
    { id: "mahapragya", name: "Mahapragya Silk Palace", defaultType: "OTH" }
  ];
  var DEFAULT_SETTINGS = { gstRegistered: false, markupPct: 60, roundTo: 50 };

  // src/data/types.ts
  var STATUS_LABEL = {
    unpriced: "Needs price",
    in_stock: "In stock",
    sold: "Sold",
    family: "Family",
    returned: "Returned"
  };

  // server/schema.ts
  var T = (key, header, width) => ({ key, header, kind: "text", width });
  var N = (key, header) => ({ key, header, kind: "num", width: 90 });
  var B = (key, header) => ({ key, header, kind: "bool", width: 80 });
  var TM = (key, header) => ({ key, header, kind: "time", width: 130 });
  var ITEMS = {
    name: "Sarees",
    cols: [
      T("id", "Saree ID", 120),
      T("type", "Type", 60),
      T("design", "Design", 180),
      { key: "status", header: "Status", kind: "status", width: 100 },
      N("price", "Price ₹"),
      N("cost", "Cost ₹"),
      T("vendorName", "Vendor", 160),
      T("purchaseDate", "Bought on", 100),
      T("purchaseId", "Purchase", 100),
      T("vendorId", "Vendor code", 100),
      B("deleted", "Deleted"),
      T("createdBy", "Added by", 90),
      TM("createdAt", "Added at"),
      T("updatedBy", "Changed by", 90),
      TM("updatedAt", "Changed at")
    ]
  };
  var PURCHASES = {
    name: "Purchases",
    cols: [
      T("id", "Purchase", 100),
      T("vendorName", "Vendor", 160),
      T("billNo", "Bill no.", 120),
      T("billDate", "Bill date", 100),
      { key: "docType", header: "Bill type", kind: "doctype", width: 100 },
      N("totalQty", "Pieces"),
      N("subtotal", "Subtotal ₹"),
      N("tax", "GST ₹"),
      N("roundOff", "Round off ₹"),
      N("grandTotal", "Grand total ₹"),
      N("adjAmount", "Deduction ₹"),
      T("adjReason", "Deduction reason", 110),
      N("amountPaid", "Paid ₹"),
      { key: "photoRefs", header: "Bill photo", kind: "photos", width: 220 },
      B("readByAi", "Read by AI"),
      B("checksOverridden", "Saved despite mismatch"),
      B("deleted", "Deleted"),
      T("vendorId", "Vendor code", 100),
      T("createdBy", "Added by", 90),
      TM("createdAt", "Added at"),
      T("updatedBy", "Changed by", 90),
      TM("updatedAt", "Changed at")
    ]
  };
  var LINES = {
    name: "Bill lines",
    cols: [
      T("purchaseId", "Purchase", 100),
      N("lineNo", "Line"),
      T("description", "Design (as printed)", 200),
      T("type", "Type", 60),
      N("qty", "Qty"),
      N("rate", "Rate ₹"),
      N("discountPct", "Disc %"),
      N("amount", "Amount ₹"),
      N("unitCost", "Cost each ₹"),
      { key: "itemIds", header: "Saree IDs", kind: "list", width: 260 },
      T("hsn", "HSN", 80)
    ]
  };
  var VENDORS = { name: "Vendors", cols: [T("id", "Code", 140), T("name", "Vendor", 200), T("defaultType", "Usual type", 90)] };
  var TYPES = { name: "Saree types", cols: [T("code", "Code", 70), T("name", "Name", 200)] };
  var PEOPLE = { name: "People", cols: [T("id", "ID", 120), T("name", "Name", 140), T("initial", "Initial", 70)] };
  var SETTINGS = { name: "Settings", cols: [B("gstRegistered", "GST registered"), N("markupPct", "Markup %"), N("roundTo", "Round prices to ₹")] };
  var COUNTERS = { name: "Counters", cols: [T("key", "Counter", 160), N("n", "Last number")] };
  var LOG = { name: "Log", cols: [T("opId", "Change ID", 240), TM("at", "When"), T("by", "Who", 90), T("action", "What", 140), T("summary", "Details", 360)] };
  var ALL_TABLES = [ITEMS, PURCHASES, LINES, VENDORS, TYPES, PEOPLE, SETTINGS, COUNTERS, LOG];
  var pad2 = (n) => String(n).padStart(2, "0");
  function fmtTime(ms) {
    const d = new Date(ms);
    return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())} ${pad2(d.getHours())}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())}`;
  }
  function parseTime(v) {
    var _a;
    if (v instanceof Date) return v.getTime();
    if (typeof v === "number") return v;
    const m = String(v != null ? v : "").match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})(?::(\d{2}))?/);
    return m ? new Date(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +((_a = m[6]) != null ? _a : 0)).getTime() : 0;
  }
  function dateText(v) {
    if (v instanceof Date) return `${v.getFullYear()}-${pad2(v.getMonth() + 1)}-${pad2(v.getDate())}`;
    return v == null ? "" : String(v);
  }
  var LABEL_TO_STATUS = Object.fromEntries(Object.entries(STATUS_LABEL).map(([k, v]) => [v.toLowerCase(), k]));
  var DOC_LABEL = { tax_invoice: "Tax invoice", quotation: "Quotation", estimate: "Estimate", other: "Other" };
  var LABEL_TO_DOC = Object.fromEntries(Object.entries(DOC_LABEL).map(([k, v]) => [v.toLowerCase(), k]));
  var driveUrl = (id) => `https://drive.google.com/file/d/${id}/view`;
  function toCell(kind, v) {
    var _a, _b;
    switch (kind) {
      case "num":
        return v == null || v === "" ? "" : Number(v);
      case "bool":
        return v === true;
      case "time":
        return typeof v === "number" && v > 0 ? fmtTime(v) : "";
      case "status":
        return (_a = STATUS_LABEL[v]) != null ? _a : String(v != null ? v : "");
      case "doctype":
        return (_b = DOC_LABEL[v]) != null ? _b : "Other";
      case "list":
        return Array.isArray(v) ? v.join(", ") : "";
      case "photos":
        return Array.isArray(v) ? v.map((id) => driveUrl(String(id))).join("\n") : "";
      default:
        return v == null ? "" : String(v);
    }
  }
  function fromCell(kind, v) {
    var _a, _b;
    switch (kind) {
      case "num":
        return v === "" || v == null ? null : Number(v);
      case "bool":
        return v === true || String(v).toUpperCase() === "TRUE";
      case "time":
        return parseTime(v);
      case "status": {
        const s = String(v != null ? v : "").trim();
        return (_a = LABEL_TO_STATUS[s.toLowerCase()]) != null ? _a : s in STATUS_LABEL ? s : "in_stock";
      }
      case "doctype":
        return (_b = LABEL_TO_DOC[String(v != null ? v : "").toLowerCase()]) != null ? _b : "other";
      case "list":
        return String(v != null ? v : "").split(/[,\s]+/).filter(Boolean);
      case "photos":
        return String(v != null ? v : "").split(/\s+/).map((u) => {
          var _a2, _b2;
          return (_b2 = (_a2 = u.match(/\/d\/([\w-]+)/)) == null ? void 0 : _a2[1]) != null ? _b2 : "";
        }).filter(Boolean);
      default:
        return dateText(v);
    }
  }
  var rowToRecord = (t, row) => Object.fromEntries(t.cols.map((c, i) => [c.key, fromCell(c.kind, row[i])]));
  var recordToRow = (t, r) => t.cols.map((c) => toCell(c.kind, r[c.key]));
  var itemFromRec = (r) => ({ ...r, deleted: r.deleted === true });
  function purchaseToRec(p) {
    var _a, _b;
    const { lines: _l, adjustment, ...rest } = p;
    return { ...rest, adjAmount: (_a = adjustment == null ? void 0 : adjustment.amount) != null ? _a : null, adjReason: (_b = adjustment == null ? void 0 : adjustment.reason) != null ? _b : "" };
  }
  function purchaseFromRec(r, lines) {
    const { adjAmount, adjReason, ...rest } = r;
    return {
      ...rest,
      adjustment: adjAmount ? { amount: Number(adjAmount), reason: String(adjReason) || "other" } : null,
      lines
    };
  }
  var lineToRec = (purchaseId2, l, i) => ({ ...l, purchaseId: purchaseId2, lineNo: i + 1 });
  function lineFromRec(r) {
    return r;
  }

  // server/main.ts
  var FORMAT = { num: "#,##0.##", bool: "General" };
  var fmtFor = (t) => t.cols.map((c) => {
    var _a;
    return (_a = FORMAT[c.kind]) != null ? _a : "@";
  });
  function book() {
    return SpreadsheetApp.getActiveSpreadsheet();
  }
  function tab(t) {
    const ss = book();
    let sh = ss.getSheetByName(t.name);
    if (sh) return sh;
    sh = ss.insertSheet(t.name);
    sh.getRange(1, 1, 1, t.cols.length).setValues([t.cols.map((c) => c.header)]).setFontWeight("bold").setBackground("#f6ebd3");
    sh.setFrozenRows(1);
    t.cols.forEach((c, i) => {
      if (c.width) sh.setColumnWidth(i + 1, c.width);
    });
    return sh;
  }
  function ensureRows(sh, lastNeeded) {
    const max = sh.getMaxRows();
    if (lastNeeded > max) sh.insertRowsAfter(max, lastNeeded - max);
  }
  function readTable(t) {
    const sh = tab(t);
    const last = sh.getLastRow();
    if (last < 2) return [];
    const values = sh.getRange(2, 1, last - 1, t.cols.length).getValues();
    return values.filter((r) => r.some((v) => v !== "" && v !== null)).map((r) => rowToRecord(t, r));
  }
  function writeRows(sh, t, startRow, recs) {
    if (!recs.length) return;
    ensureRows(sh, startRow + recs.length - 1);
    const rng = sh.getRange(startRow, 1, recs.length, t.cols.length);
    const f = fmtFor(t);
    rng.setNumberFormats(recs.map(() => f));
    rng.setValues(recs.map((r) => recordToRow(t, r)));
  }
  function writeAll(t, recs) {
    const sh = tab(t);
    const last = sh.getLastRow();
    writeRows(sh, t, 2, recs);
    if (last > recs.length + 1) sh.getRange(recs.length + 2, 1, last - recs.length - 1, t.cols.length).clearContent();
  }
  function appendRecs(t, recs) {
    const sh = tab(t);
    writeRows(sh, t, Math.max(sh.getLastRow(), 1) + 1, recs);
  }
  function readState() {
    const lines = readTable(LINES).map(lineFromRec);
    const byPurchase = /* @__PURE__ */ new Map();
    lines.forEach((l) => {
      var _a;
      return byPurchase.set(l.purchaseId, [...(_a = byPurchase.get(l.purchaseId)) != null ? _a : [], l]);
    });
    const settingsRow = readTable(SETTINGS)[0];
    return {
      users: readTable(PEOPLE),
      vendors: readTable(VENDORS),
      types: readTable(TYPES),
      settings: settingsRow ? { ...DEFAULT_SETTINGS, ...settingsRow } : DEFAULT_SETTINGS,
      purchases: readTable(PURCHASES).map((r) => {
        var _a;
        const ls = ((_a = byPurchase.get(String(r.id))) != null ? _a : []).sort((a, b) => a.lineNo - b.lineNo);
        return purchaseFromRec(r, ls.map(({ purchaseId: _p, lineNo: _n, ...l }) => l));
      }),
      items: readTable(ITEMS).map(itemFromRec)
    };
  }
  var TOUCHES = {
    saveUser: ["users"],
    saveVendor: ["vendors"],
    deleteVendor: ["vendors"],
    saveType: ["types"],
    deleteType: ["types"],
    saveSettings: ["settings"],
    setPurchaseDeleted: ["purchases", "items"],
    updateItems: ["items"]
  };
  function writeTables(s, which) {
    if (which.has("users")) writeAll(PEOPLE, s.users);
    if (which.has("vendors")) writeAll(VENDORS, s.vendors);
    if (which.has("types")) writeAll(TYPES, s.types);
    if (which.has("settings")) writeAll(SETTINGS, [s.settings]);
    if (which.has("purchases")) writeAll(PURCHASES, s.purchases.map(purchaseToRec));
    if (which.has("items")) writeAll(ITEMS, s.items);
  }
  function loggedIds() {
    const sh = tab(LOG);
    const last = sh.getLastRow();
    if (last < 2) return /* @__PURE__ */ new Set();
    return new Set(sh.getRange(2, 1, last - 1, 1).getValues().map((r) => String(r[0])));
  }
  function summarize(op) {
    switch (op.t) {
      case "updateItems":
        return `${op.ids.length} saree(s): ${JSON.stringify(op.patch)} — ${op.ids.slice(0, 6).join(", ")}${op.ids.length > 6 ? "…" : ""}`;
      case "setPurchaseDeleted":
        return `${op.id} ${op.deleted ? "deleted" : "restored"}`;
      case "saveUser":
        return op.u.name;
      case "saveVendor":
        return op.v.name;
      case "saveType":
        return `${op.type.code} ${op.type.name}`;
      case "deleteVendor":
        return op.id;
      case "deleteType":
        return op.code;
      case "saveSettings":
        return JSON.stringify(op.s);
    }
  }
  function applyOps(envs) {
    const done = loggedIds();
    let s = readState();
    const touched = /* @__PURE__ */ new Set();
    const applied = [];
    const log = [];
    for (const e of envs) {
      applied.push(e.opId);
      if (done.has(e.opId)) continue;
      s = applyOp(s, e);
      TOUCHES[e.op.t].forEach((k) => touched.add(k));
      done.add(e.opId);
      log.push({ opId: e.opId, at: e.at, by: e.by, action: e.op.t, summary: summarize(e.op) });
    }
    writeTables(s, touched);
    appendRecs(LOG, log);
    return { applied, state: s };
  }
  function savePurchase(opId, draft, by) {
    const sh = tab(LOG);
    const last = sh.getLastRow();
    if (last >= 2) {
      const rows = sh.getRange(2, 1, last - 1, 5).getValues();
      const hit = rows.find((r) => String(r[0]) === opId);
      if (hit) {
        const state = readState();
        const pid = String(hit[4]).split(" ")[0];
        const p = state.purchases.find((x) => x.id === pid);
        if (p) return { purchase: p, state };
      }
    }
    const counters = {};
    readTable(COUNTERS).forEach((r) => {
      counters[String(r.key)] = Number(r.n) || 0;
    });
    const settingsRow = readTable(SETTINGS)[0];
    const settings = settingsRow ? { ...DEFAULT_SETTINGS, ...settingsRow } : DEFAULT_SETTINGS;
    const out = buildPurchase(draft, counters, settings, { id: by, name: by, initial: "" });
    appendRecs(PURCHASES, [purchaseToRec(out.purchase)]);
    appendRecs(LINES, out.purchase.lines.map((l, i) => lineToRec(out.purchase.id, l, i)));
    appendRecs(ITEMS, out.items);
    writeAll(COUNTERS, Object.entries(out.counters).sort().map(([key, n]) => ({ key, n })));
    appendRecs(LOG, [{ opId, at: Date.now(), by, action: "savePurchase", summary: `${out.purchase.id} ${out.purchase.vendorName} bill ${out.purchase.billNo} · ${out.items.length} sarees` }]);
    return { purchase: out.purchase, state: readState() };
  }
  function photoFolder() {
    const props = PropertiesService.getScriptProperties();
    const id = props.getProperty("PHOTO_FOLDER_ID");
    if (id) {
      try {
        return DriveApp.getFolderById(id);
      } catch {
      }
    }
    const f = DriveApp.createFolder("Anavrin bill photos");
    props.setProperty("PHOTO_FOLDER_ID", f.getId());
    return f;
  }
  function savePhoto(img) {
    const name = `bill-${Date.now()}.${img.mimeType.includes("png") ? "png" : "jpg"}`;
    const blob = Utilities.newBlob(Utilities.base64Decode(img.data), img.mimeType, name);
    return photoFolder().createFile(blob).getId();
  }
  function getPhoto(id) {
    var _a;
    const b = DriveApp.getFileById(id).getBlob();
    return { data: Utilities.base64Encode(b.getBytes()), mimeType: (_a = b.getContentType()) != null ? _a : "image/jpeg" };
  }
  function parseLoose(text) {
    const t = text.trim().replace(/^```(?:json)?\s*/i, "").replace(/```$/, "");
    try {
      return JSON.parse(t);
    } catch {
    }
    const a = t.indexOf("{"), b = t.lastIndexOf("}");
    return a >= 0 && b > a ? JSON.parse(t.slice(a, b + 1)) : {};
  }
  function readBill(images) {
    var _a, _b, _c, _d;
    const props = PropertiesService.getScriptProperties();
    const key = props.getProperty("GEMINI_API_KEY");
    if (!key) throw new Error("Bill reading is not set up: add GEMINI_API_KEY in Apps Script → Project settings → Script properties.");
    const models = (props.getProperty("GEMINI_MODELS") || "gemini-3.5-flash,gemini-3.5-flash-lite").split(",").map((m) => m.trim()).filter(Boolean);
    const body = JSON.stringify({
      contents: [{ role: "user", parts: [{ text: BILL_PROMPT }, ...images.map((i) => ({ inline_data: { mime_type: i.mimeType, data: i.data } }))] }],
      generationConfig: { responseMimeType: "application/json", temperature: 0 }
    });
    let last = "";
    for (const m of models) {
      const res = UrlFetchApp.fetch(`https://generativelanguage.googleapis.com/v1beta/models/${m}:generateContent`, {
        method: "post",
        contentType: "application/json",
        headers: { "x-goog-api-key": key },
        payload: body,
        muteHttpExceptions: true
      });
      const code = res.getResponseCode();
      const text = res.getContentText();
      if (code === 200) {
        const j = JSON.parse(text);
        const out = ((_d = (_c = (_b = (_a = j.candidates) == null ? void 0 : _a[0]) == null ? void 0 : _b.content) == null ? void 0 : _c.parts) != null ? _d : []).map((p) => {
          var _a2;
          return (_a2 = p.text) != null ? _a2 : "";
        }).join("");
        return normalizeBill(parseLoose(out));
      }
      last = `${m} answered ${code}: ${text.slice(0, 200)}`;
      if (![403, 404, 429, 500, 503].includes(code)) break;
    }
    throw new Error(code429(last) ? "The free daily limit for bill reading is used up. Type this bill in, or try again tomorrow." : `Bill reading failed (${last})`);
  }
  var code429 = (s) => / 429:/.test(s);
  function json(o) {
    return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);
  }
  function handle(req) {
    const props = PropertiesService.getScriptProperties();
    const family = props.getProperty("FAMILY_KEY");
    if (!family) return { error: "Server not set up yet: run the setup function once in Apps Script." };
    if (req.key !== family) return { error: "Wrong family key. Ask whoever set up the app for the invite link.", code: "unauthorized" };
    const withLock = (fn) => {
      const lock = LockService.getScriptLock();
      lock.waitLock(3e4);
      try {
        return fn();
      } finally {
        lock.releaseLock();
      }
    };
    switch (req.action) {
      case "ping":
        return { ok: true, name: book().getName(), sheetUrl: book().getUrl() };
      case "all":
        return { state: readState(), sheetUrl: book().getUrl() };
      case "ops":
        return withLock(() => applyOps(req.ops));
      case "savePurchase":
        return withLock(() => savePurchase(String(req.opId), req.draft, String(req.by)));
      case "uploadPhoto":
        return { ref: savePhoto(req.image) };
      case "photo":
        return getPhoto(String(req.id));
      case "readBill": {
        const images = req.images.slice(0, 4);
        const photoRefs = images.map(savePhoto);
        return { bill: readBill(images), photoRefs };
      }
      default:
        return { error: `Unknown action ${String(req.action)}` };
    }
  }
  function doPost(e) {
    var _a;
    let req;
    try {
      req = JSON.parse(e.postData.contents);
    } catch {
      return json({ error: "Bad request" });
    }
    try {
      return json(handle(req));
    } catch (err) {
      return json({ error: (_a = err.message) != null ? _a : String(err) });
    }
  }
  function doGet() {
    return ContentService.createTextOutput("Anavrin server is running. Open the Anavrin app to use it.");
  }
  function setup() {
    ALL_TABLES.forEach(tab);
    const ss = book();
    const blank = ss.getSheetByName("Sheet1");
    if (blank && blank.getLastRow() === 0 && ss.getSheets().length > 1) ss.deleteSheet(blank);
    if (!readTable(TYPES).length) writeAll(TYPES, DEFAULT_TYPES);
    if (!readTable(VENDORS).length) writeAll(VENDORS, DEFAULT_VENDORS);
    if (!readTable(SETTINGS).length) writeAll(SETTINGS, [DEFAULT_SETTINGS]);
    const props = PropertiesService.getScriptProperties();
    let key = props.getProperty("FAMILY_KEY");
    if (!key) {
      key = Utilities.getUuid().replace(/-/g, "");
      props.setProperty("FAMILY_KEY", key);
    }
    photoFolder();
    const gem = props.getProperty("GEMINI_API_KEY") ? "found" : "MISSING — add it under Project settings → Script properties (see SETUP.md)";
    console.log(`Setup done.

Family key: ${key}
Gemini key: ${gem}

Next: Deploy → New deployment → Web app (Execute as: Me, Who has access: Anyone). Then paste the Web app URL and the family key into the Anavrin app.`);
    return key;
  }
  return __toCommonJS(main_exports);
})();

// ---- entry points Apps Script calls ----
function doGet(e) { return Anavrin.doGet(e) }
function doPost(e) { return Anavrin.doPost(e) }
/** Run this once after pasting the code (select "setup" above, then Run). */
function setup() { return Anavrin.setup() }
